version: '3'

networks:
  laravel:
services:
  nginx:
          build:
            context: .
            dockerfile: ./nginx/Dockerfile
          container_name: nginx
          ports:
            - "8088:80"
          volumes:
            - ./src:/var/www/html
          depends_on:
            - php
          networks:
            - default
  redis:
          build:
            context: .
            dockerfile: ./redis/Dockerfile
          container_name: redis
          volumes:
            - ./redis/redis.conf:/etc/redis/redis.conf
          networks:
            - default

  postgres:
            image: postgres
            container_name: postgres
            restart: unless-stopped
            tty: true
            ports:
              - "5433:5432"
            networks:
              - default
            environment:
              - POSTGRES_PASSWORD=secret

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile

    container_name: php

    volumes:
    - "./src:/var/www/html"
    ports:
      - "9000:9000"
    networks:
      - default
    depends_on:
      - redis
      - postgres
