version: '3'

networks:
  laravel:
services:
  nginx:
          image: nginx

          container_name: nginx

          ports:
            - "8088:80"

          volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          depends_on:
            - php
            - postgres

          networks:
            - default

  redis:
          build:
            context: .
            dockerfile: Dockerfile
          container_name: redis
          volumes:
            - ./redis/redis.conf:/etc/redis/redis.conf
          networks:
            - default

  postgres:
            image: postgres
            container_name: postgres
            restart: unless-stopped
            tty: true 
            ports:
                - "4306:3306"
            networks:
              - default
  
  php:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: php

    volumes:
    - "./src:/var/www/html"
    ports:
      - "9000:9000"
    networks:
      - default
    depends_on:
      - redis 